---
title: "EMF index"
author: "Eddy Hernandez"
date: "Today"
output: html_document
editor_options: 
  chunk_output_type: console
chunk_output_type: inline
---

RMD chunk for file sorting and creating EMF, Shannon, and Pielous indexes

```{r}

# Library and installation calls need to happen in order before multifunc can be called

library(devtools)

install_github("cran/vegetarian")
install_github("https://github.com/jebyrnes/multifunc")
install.packages("vegan")

# Vegan can be installed once and deleted after

library(dplyr)
library(vegan)
library(ggplot2)
library(tidyverse)
library(multifunc)
library(moments)
library(reshape2)

# Reads in CSV's.
# tcn is missing one sample number. Other df's have 48 entries (24 for each time point). Tcn has 23 (No T2 or T6), organized based on plot number.

# One sample from "KeggENZwID" was removed because it was empty.

lipid <- read.csv("hf303-01-lipid-p.csv")
enzymeAct <- read.csv("hf303-06-enzyme-activity.csv")
keggez <- read.csv("KeggENZwID.csv")
keggezOld <- read.csv("KeggENZwIDold.csv")

# Makes column and variable names uniform

names(lipid)[names(lipid) == "warming"] <- "treatment"
names(lipid)[names(lipid) == "soil.type"] <- "soil"
names(enzymeAct)[names(enzymeAct) == "warming"] <- "treatment"
enzymeAct$treatment[enzymeAct$treatment == "DC"] <- "C"
 
# column names in order

lipid <- lipid[,c("treatment","soil","plot","timepoint","doy","date","lipidp.dry")]
enzymeAct <- enzymeAct[,c("sample.id","treatment","soil","plot","timepoint","doy","date","enzyme","eea")]

# Creates a variable with the function names we want. Creates variable indexes with the column position of the functions we want from each data frame we are using

vars <- qw(plot,treatment,soil,timepoint,sample.id,enzyme,eea,lipidp.dry,BG,CBH,BX,NAG,PO,HPO)
varIdxEnz <- which(names(enzymeAct) %in% vars)
varIdxLip <- which(names(lipid) %in% vars)
plotorder <- c

# Subsets data frame by their time point, T2 = June, T6 = October

enzymeSimp <- subset(enzymeAct, select = varIdxEnz, enzymeAct$timepoint=="T2" | enzymeAct$timepoint == "T6")
lipidSimp <- subset(lipid, select = varIdxLip, lipid$timepoint == "T2" | lipid$timepoint == "T6")

# Turns enzyme observations into Variables PHOS was only measured at T6 so it should be omitted

enzOrg <- pivot_wider(enzymeSimp, id_cols = c("soil","timepoint","treatment", "plot", "sample.id"), names_from = enzyme, values_from = eea)
enzOrg <- subset(enzOrg, select = c(qw(plot,treatment,soil,timepoint,BG,CBH,BX,NAG,PO,HPO)))

# Creates a sample ID column for both df's

enzOrg$ID <- as.factor(paste(enzOrg$treatment, enzOrg$soil,enzOrg$timepoint,enzOrg$plot,sep = "." ))
lipidSimp$ID <- as.factor(paste(lipidSimp$treatment, lipidSimp$soil,lipidSimp$timepoint,lipidSimp$plot,sep = "." ))

# KEGG Enzyme organization and set up for Shannons H. keggezwide is a dataframe of keggez where columns and rows and rows are switched. rowtovarname is a vector containing the enzyme names. colnames changes keggezwide column names to match their respective enzyme. 
 
keggezwide <- as.data.frame(t(keggez))
rowtovarname <- as.factor(keggezwide[1,])
colnames(keggezwide) <- rowtovarname
keggezwide <- keggezwide[-c(1),]
keggezwide <- as.data.frame(sapply(keggezwide, as.numeric))
ID <- as.data.frame(as.factor(colnames(keggez[,2:29])))
colnames(ID) <- "ID"
keggezwide <- cbind.data.frame(ID, keggezwide)

# Shannons H for MetaT, -(1) = omit column 1. Original output gave "ShanDiv2", a Shannon H for all enzymes and not samples.

ShanDiv2 <- as.data.frame(diversity(keggezOld[,-(1)])) 
# Shannon Diversity calculated using keggez df
ShanDiv <- as.data.frame(diversity(keggezwide[,-(1)]))
ShanDiv <- cbind.data.frame(ID, ShanDiv)
colnames(ShanDiv) <- c("ID", "ShannonsH")
PielousEven <-  as.data.frame(diversity(keggezwide[,-(1)], index = "simpson")/log(specnumber(keggezwide[,-(1)])))
PielousEven <- cbind.data.frame(ID, PielousEven)
colnames(PielousEven) <- c("ID", "PielousJ")

# Consolidates df's "enzOrg", and "lipidSimp" 
 
organizedchart <- merge(enzOrg,lipidSimp[,c(5,6)],by = "ID")

# Gets the mean function of the enzyme and lipid samples in df "organizedchart", adds result to the end of "organizedchart"

organizedchart <-cbind(organizedchart, getStdAndMeanFunctions(organizedchart ,c("BG","CBH","BX","NAG","PO","HPO","lipidp.dry"), standardizeZScore))

# Mergens diversity index' "ShanDiv" for Shannon alpha diversity and "PielousEven" for Pielous evenness

organizedchart <- merge(organizedchart,ShanDiv,by = "ID", all.x = FALSE)
organizedchart <- merge(organizedchart,PielousEven,by = "ID", all.x = FALSE)

```

```{r fig.width=1, fig.height=1 }
ggplot(organizedchart, aes( ShannonsH, meanFunction))+geom_point(size = 1)+ geom_line()
  theme_bw(base_size=5)+
  xlab("Shannons H") +
  ylab("System Mean Function")
```

```{r}

# Plots Shannons H (X) by Mean Function (Y), seperates color points by treatment, geom smooth adds a linear model to chart. Facet wrap separates charts by horizon

organizedchart %>%
    ggplot(aes(ShannonsH, meanFunction, 
               colour = treatment)) +
    geom_point( size = 3, alpha = 0.5) +
    geom_smooth(method = lm, se = T) +
    facet_wrap(~soil) +
    labs(x = "Enzymatic Diversity", y = "Multifunctionality")
```

```{r}

# Plots Shannons H (X) by Mean Function (Y), seperates color points by treatment, geom smooth adds a linear model to chart. Facet wrap separates charts by timepoint

organizedchart %>%
    ggplot(aes(ShannonsH, meanFunction, 
               colour = treatment)) +
    geom_point( size = 3, alpha = 0.5) +
    geom_smooth(method = lm, se = T) +
    facet_wrap(~ timepoint) +
    labs(x = "Enzymatic Diversity", y = "Multifunctionality")
```

```{r}

# Plots Pielous J (X) by Mean Function (Y), separates color points by treatment, geom smooth adds a linear model to chart. Facet wrap separates charts by horizon

organizedchart %>%
    ggplot(aes( PielousJ, meanFunction, 
               colour = treatment)) +
    geom_point( size = 3, alpha = 0.5) +
    geom_smooth(method = lm, se = T) +
    facet_wrap(~timepoint) +
    labs(x = "Enzymatic Evenness", y = "Multifunctionality")
```

```{r}

# Plots Pielous J (X) by Mean Function (Y), separates color points by treatment, geom smooth adds a linear model to chart. Facet wrap separates charts by timepoint

organizedchart %>%
    ggplot(aes( PielousJ, meanFunction, 
               colour = treatment)) +
    geom_point( size = 3, alpha = 0.5) +
    geom_smooth(method = lm, se = T) +
    facet_wrap(~soil) +
    labs(x = "Enzymatic Evenness", y = "Multifunctionality")
```